### ISSUE TITLE
New Discord CDN Standard

### ISSUE THREAD

**Issue by JustAHippo** [DisboxApp/server#3]
Discord has currently implemented 3 parameters for all CDN links
ex, is, and hm
Right now, none of these fields are mandatory, however all will be in the future. They cycle once per day to prevent outside links from being used to spread things like malicious programs. This means that simply storing the CDN links to the files will no longer be enough.

In order to combat this, we need a way to read back the messages that contain each file whenever it is requested, rather than caching the CDN links. Is there a way this could be implemented efficiently?

**Comment by DisboxApp** [comment]
This is already implemented. Disbox stores message IDs, not CDN links. CDN links are only stored for sharing files.
